import SideBarComponent from "@/components/sidebar/SideBarPage";
import "../globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <body className="flex">
      <aside className="h-screen">
        <SideBarComponent />
      </aside>
      <main className="flex-1">
        <section>
          {children}
        </section>
      </main>
      </body>
      </html>
  )
}
